// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfj0yN8XYqm6IHjcLrxSbQBYbF9OOXB6A',
    appId: '1:26093214497:android:d8abb6a675fde5c9eafc60',
    messagingSenderId: '26093214497',
    projectId: 'fir-auth-2df4c',
    storageBucket: 'fir-auth-2df4c.appspot.com',
    databaseURL:
        'https://fir-auth-2df4c-default-rtdb.asia-southeast1.firebasedatabase.app', // Updated databaseURL
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWawzzCWH3vDz-uA-yTCslrbqO433htE',
    appId: '1:26093214497:ios:8d2779df155c6832eafc60',
    messagingSenderId: '26093214497',
    projectId: 'fir-auth-2df4c',
    storageBucket: 'fir-auth-2df4c.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
    databaseURL:
        'https://fir-auth-2df4c-default-rtdb.asia-southeast1.firebasedatabase.app', // Updated databaseURL
  );
}
